### ISSUE TITLE
📚 [Documentation] - Rethinking Project Roles

### ISSUE THREAD

**Issue by jennyreddish** [Seshat-Global-History-Databank/seshat#150]
### Section of Documentation

Researcher, Seshat Expert, Public User, Team

### Description of Improvement

We should collectively think about the roles we define for the project, and the names we use for them. For most of the project's lifetime, "Seshat expert" has referred to external collaborators -- historians, archaeologists and so on -- who give feedback on our data and suggest changes based on their expertise. E.g. see https://seshatdatabank.info/seshat-about-us/contributor-database. However, on the ~~SQL~~ Seshat website and the Documentation, we seem to be using it to refer to internal team members with admin privileges, like Peter Turchin. Suggest keeping "Seshat expert" for external historians etc., and using something else for team members. To discuss.

### Benefits of Improvement

Clearer definition of the various roles associated with the project

### Definition of Done

- [x] The documentation improvement has been developed on a branch.
- [x] A pull request has been created for the new branch to be merged into the dev branch.

**Comment by edwardchalstrey1** [comment]
Since there is not likely to be any particular documentation specific to the Seshat Expert or Public User roles, I may remove these sections entirely and simply move all the "Researcher" docs to the top level of the documentation pages toctree (contents). We can still include these [role](https://seshat-global-history-databank.github.io/seshat/index.html#project-roles) descriptions to help direct people to the right pages e.g. saying for External users, the only relevant page will be [Getting Started with Seshat data](https://seshat-global-history-databank.github.io/seshat/researcher/getting_started.html). But basically for everyone else all the documentation is useful, with the exception of the pages under "Seshat Databank Admin".
